services:
  nginx:
    image: nginx:latest
    ports:
      - "5080:80"
      - "5443:443"
    volumes:
      - ./loginm/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl